### ISSUE TITLE
A question about evaluator

### ISSUE THREAD

**Issue by Jason001028** [PiggyCh/RL-MADDPG-navigation-gird-world#1]
Hi，bro
Have you been in a situation like this before?I tried to run the train.py.As expected, there will be 8 actors and 1 evaluator window, but when the code runs for about 7 minutes, the following error occurs, causing the actor to run properly and the evaluator to stop working:

Process SpawnProcess-10:
Traceback (most recent call last):
  File "D:\Anaconda\envs\py38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Anaconda\envs\py38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\RL-MADDPG-navigation-grid-world-main\core\evaluator.py", line 45, in evaluate_worker
    data = evalue_queue.get()
  File "D:\Anaconda\envs\py38\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "D:\Anaconda\envs\py38\lib\site-packages\torch\multiprocessing\reductions.py", line 324, in rebuild_storage_filename
    storage = torch.UntypedStorage._new_shared_filename_cpu(manager, handle, size)
RuntimeError: Couldn't open shared event: <000001AAD60CA242>, error code: <2>

**Comment by PiggyCh** [comment]
not yet, but I guess two prob reason: 
 1. memory maybe exceed, bigger prob if the server memory is less than 32G.
 2. pytorch version
 for 1, I suggest decrese the worker num and the memory size, set in arguments.py  
 for 2. try to degrade the pytorch version , maybe 1.7 \1,8.
